apiVersion: batch/v1
kind: Job
metadata:
  name: emanager-apitest-job
spec:
  template:
    spec:
      containers:
      - name: emanager-apitest-container
        image: sreenath5007/alpha:emanager-apitest-v1.0.2
        env:
        - name: SERVICE_ENDPOINT
          value: "http://emanager-serv-service:80"  # Replace with the correct service endpoint
        volumeMounts:
        - name: report-volume
          mountPath: /app
        command: ["sh", "-c", "newman run /app/apicollections.json -d /app/TestData.csv -n 2 --delay-request 500 -r htmlextra --reporter-htmlextra-title 'API Suite Report' --reporter-htmlextra-export /app/report.html --env-var serviceEndPoint=$SERVICE_ENDPOINT && sh "]
      restartPolicy: Never
      volumes:
      - name: report-volume
        emptyDir: {}
  backoffLimit: 1
